### PR TITLE
AEROGEAR-2016 label serviceinstance

### PR DESCRIPTION
**Pull request by pb82**
We need to add a label with the service name to the service instance for the mobile cli.

ping @dimitraz @maleck13

last one ;)

### CODE REVIEW

**Comment by dimitraz** [comment]
@pb82 this is working, but the cli expects a service name of `aerogear-digger-apb`

**Comment by pb82** [comment]
@dimitraz Ok, all the other service names are without the `-apb`. Do you know why the CLI expects this? Because the name of the secret is just `aerogear-digger`: https://github.com/aerogearcatalog/aerogear-digger-apb/blob/master/roles/provision-buildfarm-apb/templates/aerogear-digger.secret.yaml.j2#L4

**Comment by maleck13** [comment]
@pb82 It is because of this https://github.com/aerogearcatalog/aerogear-digger-apb/blob/master/apb.yml#L11

**Comment by pb82** [comment]
@maleck13 @dimitraz thanks, updated.

**Comment by pb82** [comment]
For some reason the apb tool adds newlines to the Dockerfile after every build. Removed those newlines.

**Pull request merged**
